### ISSUE TITLE
OutsetaApiClient is not a constructor

### ISSUE THREAD

**Issue by mwilliams1188** [tiltcamp/outseta-api-client#16]
I'm getting the error 'OutsetaApiClient is not a constructor' when trying to initialize in firebase. Is this library ready to go? Below is my code:

`var OutsetaApiClient = require('outseta-api-client')

const outseta = new OutsetaApiClient({
  subdomain: 'mycompany',
  apiKey: functions.config().outseta.key,
  secretKey: functions.config().outseta.secret
})`

**Comment by mattwebbio** [comment]
Hey Mike! 

I'm using this library in my own app, but I'm using ES6 imports in a browser runtime. Here's a working example that I just tested in Node 14; notice the `.default` on the require statement and the fetch polyfill - I'll update the example in the readme to reflect these.

```javascript
globalThis.fetch = require('node-fetch');
var OutsetaApiClient = require('outseta-api-client').default;

const outseta = new OutsetaApiClient({
  subdomain: 'mycompany',
  apiKey: functions.config().outseta.key,
  secretKey: functions.config().outseta.secret
});

outseta.crm.accounts.getAll().then((accounts) => {
  console.log(accounts);
});
```

**Comment by mattwebbio** [comment]
Closing - let me know if you encounter any other issues!

**Comment by ap1969** [comment]
Hi,
That's weird, I'm getting this in an ES6 import:

```
import OutsetaApiClient from 'outseta-api-client';
const client = new OutsetaApiClient({
    subdomain: 'admin-tool',
    apiKey: process.env.OUTSETA_KEY,
    secretKey: process.env.OUTSETA_SECRET,
});
```

Same error: "OutsetaApiClient is not a constructor"

**Comment by ap1969** [comment]
@mattwebbio In fact, even using your code in Node 14 results in "Must use import to load ES Module" for node-fetch

**Comment by ap1969** [comment]
Ah. I had to downgrade to node-fetch v2.x.x for it to work in ES5.
