### ISSUE TITLE
Error: The API client was not initialized with API keys.

### ISSUE THREAD

**Issue by saltcod** [tiltcamp/outseta-api-client#20]
Hey! 

Super excited to find this! Looking to integrate with a NextJS site and looks like you've got a TON of work done here! 

I think I might be setting things up wrong.
I've got a .env.local where I have my api key and secret stored. I'm calling the api like this:

```
export async function getServerSideProps({ req }) {
	const client = new OutsetaApiClient({
		subdomain: "namehere",
		apiKey: process.env.OUTSETA_API_KEY,
		secretKey: process.env.OUTSETA_API_SECRET,
	});
	const people = await client.crm.people.getAll();

	console.log(people);
	/* if user is present, do something with the user data here */
	return {
		props: { people },
	};
}
```

And I'm getting this in the console:
```Error: The API client was not initialized with API keys.```

Any ideas off hand? 

Thank you so much for all your hard work on this! Amazing job.

**Comment by saltcod** [comment]
And I'm an idiot.  I had an error in the api key. 

Sorry for this!

**Comment by mattwebbio** [comment]
Glad you got it working 🥳

Let me know if you catch anything else!
